"""Tickets approved by Admin

Revision ID: 482f439ef1a1
Revises: 6b90632dfbea
Create Date: 2024-08-04 23:02:13.412504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482f439ef1a1'
down_revision = '6b90632dfbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_estimate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('time_estimate')
        batch_op.drop_column('approved_by_admin')

    # ### end Alembic commands ###
